### ISSUE TITLE
build fails with gcc-15 (C23 standard)

### ISSUE THREAD

**Issue by drew-parsons** [glotzerlab/gsd#469]
### Description

gsd 4.2.0 fails to build with gcc 15.2.0.

The error message looks like it might be a violation of the C23 C standard (implicit-function-declaration), which is now default in gcc-15.

### Script

```python
python3.13 -m build --skip-dependency-check --no-isolation --wheel
```

### Output

```shell
running build_ext
building 'gsd.fl' extension
creating build/temp.linux-x86_64-cpython-313/gsd
x86_64-linux-gnu-gcc -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/home/drew/projects/debichem/build/python-gsd=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -DPy_LIMITED_API=51052544 -Igsd -I/usr/lib/x86_64-linux-gnu/python3-numpy/numpy/_core/include -I/usr/include/python3.13 -c gsd/fl.c -o build/temp.linux-x86_64-cpython-313/gsd/fl.o
gsd/fl.c: In function ‘__Pyx_PyCode_New’:
gsd/fl.c:706:9: error: implicit declaration of function ‘PyUnstable_Code_NewWithPosOnlyArgs’ [-Wimplicit-function-declaration]
  706 |         PyUnstable_Code_NewWithPosOnlyArgs
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gsd/fl.c:704:12: error: assignment to ‘PyCodeObject *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  704 |     result =
      |            ^
gsd/fl.c: In function ‘__Pyx_CyOrPyCFunction_GET_SELF’:
gsd/fl.c:830:51: error: ‘PyCFunctionObject’ undeclared (first use in this function); did you mean ‘PyCFunction_Check’?
  830 | #define __Pyx_CyOrPyCFunction_GET_FLAGS(func)  (((PyCFunctionObject*)(func))->m_ml->ml_flags)
      |                                                   ^~~~~~~~~~~~~~~~~
gsd/fl.c:832:13: note: in expansion of macro ‘__Pyx_CyOrPyCFunction_GET_FLAGS’
  832 |     return (__Pyx_CyOrPyCFunction_GET_FLAGS(func) & METH_STATIC) ? NULL : ((PyCFunctionObject*)func)->m_self;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected output

The build should proceed without error.

### Platform

Linux

### Installation method

Compiled from source

### GSD

4.2.0

### Python version

3.13.8

**Comment by joaander** [comment]
Not a bug in GSD. `fl.c` is generated by Cython.
